### ISSUE TITLE
Unable to invoke with file to edit / view

### ISSUE THREAD

**Issue by sogaiu** [sogaiu/janet-neovim-trial-kit#1]
Would be nice if one could invoke as:

```
jpm run neovim sample.janet
```

and have `sample.janet` opened when `nvim` has started up.

Thanks to @Grazfather for the idea.

**Comment by sogaiu** [comment]
I looked into implementing this and it turns out that it's possible though a bit weird.

I was thinking that just passing any additional arguments along to the `nvim` invocation might be sensible, but IIUC, currently it would only work with one argument.  This might be the most likely usage, but it looks like it might have a bit of an unintended side-effect (possibly harmless in most cases).

I'm intending to inquire about whether jpm might be modified appropriately (or possibly whether there isn't a better way).

**Comment by bakpakin** [comment]
Not really sure how I feel about this - is it really needed or can you just create a directory `scripts/` and put things there? I know `npm` has the whole set of scripts there but I don't know it really makes sense. For Makefiles, I usually only put script-like things if they don't take argumnets - i.e. `make build`, `make clean`, `make test`, `make deploy`, `make setup-docker`, etc where CLI args are not really something I want.

For more complicated scripts, I have a `tools/` directory or similar.

**Comment by sogaiu** [comment]
Thanks for your thoughts.

I'm thinking to try to reduce prerequisites as that might lower the barrier-to-trial overall.

May be I can get away without `jpm` and/or `spork` if `conjure` gains the ability to talk to `janet` without `netrepl`.

**Comment by sogaiu** [comment]
Ok, I've hacked together support in Conjure to talk to `janet` via stdio.  This makes it so that the prerequisites can be reduced.  Specifically, `jpm` and `spork` are no longer required and the content of `project.janet` has been changed into an ordinary janet script named `jntk`.

It's now possible to start things by:

```
janet jntk sample.janet
```

or in general:

```
janet jntk [...]
```

The `[...]` content will just get passed along to `nvim`, addressing the current issue, but also providing more access to `nvim`'s cli invocation machinery.

There is a [branch](https://github.com/sogaiu/janet-neovim-trial-kit/tree/remove-jpm-and-spork) with this work on it.

I'll ask Olical if adding a stdio transport to Conjure for Janet is acceptable.

**Comment by sogaiu** [comment]
Conjure v4.49.0 now has a stdio-based option for working with janet and this project now uses that by default.

It's thus now possible to request that a specific file be open in the editor at startup as mentioned above:

```
janet jntk sample.janet
```
