### ISSUE TITLE
Doesn't clean up config and data directories when done

### ISSUE THREAD

**Issue by sogaiu** [sogaiu/janet-neovim-trial-kit#2]
A successful invocation of `jpm run neovim` leads to the creation of the following directories (and content within):

* `~/.local/share/janet-neovim-trial-kit`
* `~/.config/janet-neovim-trial-kit`

...at least on typical Linux machines

These directories (and the contained content) remain in place after `nvim` exits.

It might be nicer if there were a way for the content to be cleaned up when one is finished.

As a cautious type, I'm wary of deleting things automatically, but can appreciate wanting this ability.

Will think more on how this might be done.

Thanks to @Grazfather for the idea.

**Comment by Grazfather** [comment]
Could use `jpm run cleanup`?

**Comment by sogaiu** [comment]
Yeah, as far as a specific way to provide an invocation, that could work, thanks.

I'll try to think about how deletion might actually be carried out that I'm comfortable with (so only exactly the things that are intended for deletion are touched and nothing else).  There's no built-in way in Janet to delete a directory that's populated AFAIK.

**Comment by Grazfather** [comment]
Ah, didn't know that. To me it makes sense/is safe to remove directories that you add in ~/.local and ~/.config if they're 'namespaced' and clearly from your project. In fact I think it's a pretty typical way to clean up after yourself.

Hell, you could just have a command that lists which dirs to delete so that the user can decide to do it himself.

**Comment by sogaiu** [comment]
> you could just have a command that lists which dirs to delete so that the user can decide to do it himself.

Ah thanks for this idea.  If I don't come up with a better idea soon, I'll probably do this one.

Another idea (not necessarily mutually exclusive) might be to output a message mentioning the list of directories to delete upon completion of `jpm run neovim`.

If I could figure out how to get neovim to use some of the subdirectories of the cloned repository directory instead of things under `~/.config` and `~/.local/share`, perhaps that would be the nicest arrangement.  It seems like then it would be easy to clean up completely (just remove the cloned directory) as well as start over.

**Comment by sogaiu** [comment]
Along the lines of:

> how to get neovim to use some of the subdirectories of the cloned repository directory instead of things under ~/.config and ~/.local/share

Perhaps modifying various `XDG_*` environment variables before launching `nvim` could work:

```
Standard Paths                                  standard-path

Nvim stores configuration, data, and logs in standard locations. Plugins are
strongly encouraged to follow this pattern also. Use stdpath() to get the
paths.

                                                base-directories xdg
The "base" (root) directories conform to the XDG Base Directory Specification.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
The $XDG_CONFIG_HOME, $XDG_DATA_HOME, $XDG_RUNTIME_DIR, $XDG_STATE_HOME,
$XDG_CACHE_HOME, $XDG_CONFIG_DIRS and $XDG_DATA_DIRS environment variables
are used if defined, else default values (listed below) are used.
```

Probably should check how well that works on Windows too.

**Comment by sogaiu** [comment]
Ok, I think [this branch](https://github.com/sogaiu/janet-neovim-trial-kit/tree/isolate-in-cloned-dir-2) has something that works.

If this was done appropriately, everything except `$XDG_RUNTIME_DIR` lives inside the cloned repository directory.  IIUC, the content of the exception (`stdpath("run")`) usually lives in a temporary directory anyway, so may be leaving that alone is fine.

Will let this settle a bit, but currently I'm inclined to go with this or similar approach.  It seems it's a bit more "localized" (or "portable" in one of the senses used in the Windows world among certain enthusiasts).

**Comment by sogaiu** [comment]
I've merged the changes from [this branch](https://github.com/sogaiu/janet-neovim-trial-kit/tree/isolate-in-cloned-dir-2).

Now that relevant additional files and directories all live inside the directory that was created upon cloning, "cleaning up" should be easier.

Two types of cleaning that occur to me are:

1. Want to remove all traces - finished with the kit
2. Want a fresh start - still want to use the kit

Case 1 can be done by just removing the cloned directory as all [1] additional files and directories that got added by running `jpm run neovim` live under the cloned directory.
 
Case 2 can be done now by:

```
git clean -ff .
```

This should remove relevant [1] new files and directories that got added as a result of running `jpm run neovim`.  Another way to achieve the same end is to remove the cloned directory and reclone.

I suppose this could be made more convenient to invoke by adding a task to `project.janet`, but I'll wait for a request :)

---

[1] As mentioned [here](https://github.com/sogaiu/janet-neovim-trial-kit/issues/2#issuecomment-1765575642) there is a directory that lives outside of the clone subdirectory, but IIUC it lives in a `/tmp`-like location.  Those kinds of things seem to get cleaned up automatically (at least on typical Linux systems).

**Comment by sogaiu** [comment]
I've updated the README to include the steps mentioned in [this comment](https://github.com/sogaiu/janet-neovim-trial-kit/issues/2#issuecomment-1770745385) for the two cases of "cleaning up".

@Grazfather I'm going to close this issue now, but if it isn't working or there is something else amiss, please mention it.  Thanks again for the idea and discussion.
